### ISSUE TITLE
OSError: input_filepath  does not exist

### ISSUE THREAD

**Issue by Ruptie** [Troptrap/MoneyPrinter-Enhanced#10]
When generating a video I get this error:

Traceback (most recent call last):
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MoneyPrinter-Enhanced-main\Backend\main.py", line 333, in generate
    process_music(music_file)
  File "C:\MoneyPrinter-Enhanced-main\Backend\tiktokvoice.py", line 230, in process_music
    tfm.build(input_file, lowvol_file)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\sox\transform.py", line 593, in build
    input_format, input_filepath = self._parse_inputs(
                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\sox\transform.py", line 493, in _parse_inputs
    file_info.validate_input_file(input_filepath)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\sox\file_info.py", line 248, in validate_input_file
    raise IOError(
OSError: input_filepath  does not exist.

The input_filepath is blank.

I should probably add that I also installed google.generativeai manually and added the libmad-0.dll and libmp3lame-0.dll to the sox directory because of previous errors I was able to troubleshoot alone.

**Comment by Troptrap** [comment]
Sox is a problem on Windows, as far as I understood from other people. I do not have have a windows system at hand currently, but it needs a tutorial on its own for installation.
Probably the problem with input_filepath is created by backslashes. 
If you look at code, I'm using relative paths, Unix style, for both the web part and the filesystem part. I'm not sure how to handle the paths correctly. I think os.path is the best way, I will try to change stuff so it won't create any more problems

**Comment by Troptrap** [comment]
I just pushed a change that should solve the specific problem in your issue, but it's not guaranteed for the rest of code. Will update ASAP

**Comment by Ruptie** [comment]
Tested it and now the error is different:

Traceback (most recent call last):
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MoneyPrinter-Enhanced-main\Backend\main.py", line 333, in generate
    process_music(music_file)
  File "C:\MoneyPrinter-Enhanced-main\Backend\tiktokvoice.py", line 230, in process_music
    tfm.build(input_file, lowvol_file)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\sox\transform.py", line 593, in build
    input_format, input_filepath = self._parse_inputs(
                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\sox\transform.py", line 496, in _parse_inputs
    input_format['channels'] = file_info.channels(input_filepath)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\sox\file_info.py", line 82, in channels
    output = soxi(input_filepath, 'c')
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python312\Lib\site-packages\sox\core.py", line 153, in soxi
    raise SoxiError("SoXI failed with exit code {}".format(cpe.returncode))
sox.core.SoxiError: SoXI failed with exit code 1

**Comment by Troptrap** [comment]
Can  you confirm that sox works in cmd? For example:
`sox -v 0.5 some.mp3 out.mp3` 
This should reduce the volume of a file named `some.mp3` at 50% and save as new file `out.mp3`

**Comment by Ruptie** [comment]
Yup, sox works as intended, just tested it out with an mp3 song

**Comment by Troptrap** [comment]
It should be fixed now
